package cl.felipecastillof.qrreader.common

object Const {

    const val ABRE_MAIN = "abre_main"
    const val ABRE_ESCANEAR_QR = "abre_escanear_qr"

    const val URL_SERVER="http://192.168.68.119:9030"

    const val PREF_NOMBRE="verifacil"
    const val PREF_RESULTADO_VALIDACION="resultadoValidacion"
    const val PREF_CODIGO_A_VALIDAR="codigo_a_validar"
    const val PREF_IDSOLICITUD="pref_idsolicitud"
    const val PREF_CODVALIDACION="pref_codvalidacion"

    const val PREF_VERIF_RUT="PREF_VERIF_RUT"
     const val PREF_VERIF_NOMBRE="PREF_VERIF_NOMBRE"
     const val PREF_VERIF_APELLIDOS="PREF_VERIF_APELLIDOS"
     const val PREF_VERIF_EMAIL="PREF_VERIF_EMAIL"
     const val PREF_VERIF_CELULAR="PREF_VERIF_CELULAR"
     const val PREF_VERIF_DIRECCION="PREF_VERIF_DIRECCION"
     const val PREF_VERIF_LAT="PREF_VERIF_LAT"
     const val PREF_VERIF_LNG="PREF_VERIF_LNG"

     const val PREF_VERIF_ESTADO="PREF_VERIF_ESTADO"
     const val PREF_VERIF_IDSOLICITUD="PREF_VERIF_IDSOLICITUD"
     const val PREF_VERIF_FECHACREACION="PREF_VERIF_FECHACREACION"

     const val PREF_VERIF_FOTOCALLE="PREF_VERIF_FOTOCALLE"
     const val PREF_VERIF_FOTOCONDOMINIO="PREF_VERIF_FOTOCONDOMINIO"
     const val PREF_VERIF_FOTOENTRADA="PREF_VERIF_FOTOENTRADA"
     const val PREF_VERIF_FOTOINTERIOR="PREF_VERIF_FOTOINTERIOR"
     const val PREF_VERIF_FOTOPANORAMICA="PREF_VERIF_FOTOPANORAMICA"
     const val PREF_VERIF_FOTOCUENTA1="PREF_VERIF_FOTOCUENTA1"
     const val PREF_VERIF_FOTOCUENTA2="PREF_VERIF_FOTOCUENTA2"
     const val PREF_VERIF_FOTOPERSONALIZADA="PREF_VERIF_FOTOPERSONALIZADA"
     const val PREF_VERIF_FOTOPERSONALIZADAGLOSA="PREF_VERIF_FOTOPERSONALIZADAGLOSA"
     const val PREF_VERIF_TOLERANCIA="PREF_VERIF_TOLERANCIA"
     const val PREF_VERIF_TIPOVERIFICACION="PREF_VERIF_TIPOVERIFICACION"

}